# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rl.proto import minimetro_pb2 as rl_dot_proto_dot_minimetro__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rl/proto/minimetro_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RLEnvStub(object):
    """RLEnv exposes a single Mini Metro game instance for RL training.

    Typical usage per worker:
    1. Call Info() once at startup to validate constants.
    2. Call Reset() to begin an episode and receive the first observation.
    3. Open a RunEpisode stream: send ActionRequests, receive StepResponses
    until done=true.  Then call Reset() again for the next episode.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Info = channel.unary_unary(
                '/rl.RLEnv/Info',
                request_serializer=rl_dot_proto_dot_minimetro__pb2.Empty.SerializeToString,
                response_deserializer=rl_dot_proto_dot_minimetro__pb2.InfoResponse.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/rl.RLEnv/Reset',
                request_serializer=rl_dot_proto_dot_minimetro__pb2.ResetRequest.SerializeToString,
                response_deserializer=rl_dot_proto_dot_minimetro__pb2.ResetResponse.FromString,
                _registered_method=True)
        self.RunEpisode = channel.stream_stream(
                '/rl.RLEnv/RunEpisode',
                request_serializer=rl_dot_proto_dot_minimetro__pb2.ActionRequest.SerializeToString,
                response_deserializer=rl_dot_proto_dot_minimetro__pb2.StepResponse.FromString,
                _registered_method=True)
        self.SolverAct = channel.unary_unary(
                '/rl.RLEnv/SolverAct',
                request_serializer=rl_dot_proto_dot_minimetro__pb2.Empty.SerializeToString,
                response_deserializer=rl_dot_proto_dot_minimetro__pb2.ActionResponse.FromString,
                _registered_method=True)


class RLEnvServicer(object):
    """RLEnv exposes a single Mini Metro game instance for RL training.

    Typical usage per worker:
    1. Call Info() once at startup to validate constants.
    2. Call Reset() to begin an episode and receive the first observation.
    3. Open a RunEpisode stream: send ActionRequests, receive StepResponses
    until done=true.  Then call Reset() again for the next episode.
    """

    def Info(self, request, context):
        """Info returns environment constants for startup validation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Reset starts a new episode and returns the initial observation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunEpisode(self, request_iterator, context):
        """RunEpisode is a bidirectional stream for the inner training loop.
        The client sends one ActionRequest per step; the server replies with
        one StepResponse.  The stream stays open across steps within one episode.
        When done=true in a StepResponse, call Reset() to begin the next episode
        (the stream can be reused — send the next action after Reset returns).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SolverAct(self, request, context):
        """SolverAct returns the action the heuristic solver would take in the
        current state without advancing the simulation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RLEnvServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=rl_dot_proto_dot_minimetro__pb2.Empty.FromString,
                    response_serializer=rl_dot_proto_dot_minimetro__pb2.InfoResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=rl_dot_proto_dot_minimetro__pb2.ResetRequest.FromString,
                    response_serializer=rl_dot_proto_dot_minimetro__pb2.ResetResponse.SerializeToString,
            ),
            'RunEpisode': grpc.stream_stream_rpc_method_handler(
                    servicer.RunEpisode,
                    request_deserializer=rl_dot_proto_dot_minimetro__pb2.ActionRequest.FromString,
                    response_serializer=rl_dot_proto_dot_minimetro__pb2.StepResponse.SerializeToString,
            ),
            'SolverAct': grpc.unary_unary_rpc_method_handler(
                    servicer.SolverAct,
                    request_deserializer=rl_dot_proto_dot_minimetro__pb2.Empty.FromString,
                    response_serializer=rl_dot_proto_dot_minimetro__pb2.ActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rl.RLEnv', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rl.RLEnv', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RLEnv(object):
    """RLEnv exposes a single Mini Metro game instance for RL training.

    Typical usage per worker:
    1. Call Info() once at startup to validate constants.
    2. Call Reset() to begin an episode and receive the first observation.
    3. Open a RunEpisode stream: send ActionRequests, receive StepResponses
    until done=true.  Then call Reset() again for the next episode.
    """

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.RLEnv/Info',
            rl_dot_proto_dot_minimetro__pb2.Empty.SerializeToString,
            rl_dot_proto_dot_minimetro__pb2.InfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.RLEnv/Reset',
            rl_dot_proto_dot_minimetro__pb2.ResetRequest.SerializeToString,
            rl_dot_proto_dot_minimetro__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunEpisode(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/rl.RLEnv/RunEpisode',
            rl_dot_proto_dot_minimetro__pb2.ActionRequest.SerializeToString,
            rl_dot_proto_dot_minimetro__pb2.StepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SolverAct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.RLEnv/SolverAct',
            rl_dot_proto_dot_minimetro__pb2.Empty.SerializeToString,
            rl_dot_proto_dot_minimetro__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
