# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rl.proto import minimetro_pb2 as rl_dot_proto_dot_minimetro__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rl/proto/minimetro_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RLEnvStub(object):
    """RLEnv exposes a single Mini Metro game instance for RL training.

    Typical usage per worker:
    1. Call Info() once at startup to validate constants.
    2. Call Reset() to begin an episode and receive the first observation.
    3. Open a RunEpisode stream: send ActionRequests, receive StepResponses
    until done=true.  Then call Reset() again for the next episode.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Info = channel.unary_unary(
                '/rl.RLEnv/Info',
                request_serializer=rl_dot_proto_dot_minimetro__pb2.Empty.SerializeToString,
                response_deserializer=rl_dot_proto_dot_minimetro__pb2.InfoResponse.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/rl.RLEnv/Reset',
                request_serializer=rl_dot_proto_dot_minimetro__pb2.ResetRequest.SerializeToString,
                response_deserializer=rl_dot_proto_dot_minimetro__pb2.ResetResponse.FromString,
                _registered_method=True)
        self.RunEpisode = channel.stream_stream(
                '/rl.RLEnv/RunEpisode',
                request_serializer=rl_dot_proto_dot_minimetro__pb2.ActionRequest.SerializeToString,
                response_deserializer=rl_dot_proto_dot_minimetro__pb2.StepResponse.FromString,
                _registered_method=True)
        self.ResetVector = channel.unary_unary(
                '/rl.RLEnv/ResetVector',
                request_serializer=rl_dot_proto_dot_minimetro__pb2.VectorResetRequest.SerializeToString,
                response_deserializer=rl_dot_proto_dot_minimetro__pb2.VectorResetResponse.FromString,
                _registered_method=True)
        self.RunVectorEpisode = channel.stream_stream(
                '/rl.RLEnv/RunVectorEpisode',
                request_serializer=rl_dot_proto_dot_minimetro__pb2.VectorActionRequest.SerializeToString,
                response_deserializer=rl_dot_proto_dot_minimetro__pb2.VectorStepResponse.FromString,
                _registered_method=True)


class RLEnvServicer(object):
    """RLEnv exposes a single Mini Metro game instance for RL training.

    Typical usage per worker:
    1. Call Info() once at startup to validate constants.
    2. Call Reset() to begin an episode and receive the first observation.
    3. Open a RunEpisode stream: send ActionRequests, receive StepResponses
    until done=true.  Then call Reset() again for the next episode.
    """

    def Info(self, request, context):
        """Info returns environment constants for startup validation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Reset starts a new episode and returns the initial observation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunEpisode(self, request_iterator, context):
        """RunEpisode is a bidirectional stream for the inner training loop.
        The client sends one ActionRequest per step; the server replies with
        one StepResponse.  The stream stays open across steps within one episode.
        When done=true in a StepResponse, call Reset() to begin the next episode
        (the stream can be reused — send the next action after Reset returns).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetVector(self, request, context):
        """Vectorized endpoints for scaling throughput.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunVectorEpisode(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RLEnvServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=rl_dot_proto_dot_minimetro__pb2.Empty.FromString,
                    response_serializer=rl_dot_proto_dot_minimetro__pb2.InfoResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=rl_dot_proto_dot_minimetro__pb2.ResetRequest.FromString,
                    response_serializer=rl_dot_proto_dot_minimetro__pb2.ResetResponse.SerializeToString,
            ),
            'RunEpisode': grpc.stream_stream_rpc_method_handler(
                    servicer.RunEpisode,
                    request_deserializer=rl_dot_proto_dot_minimetro__pb2.ActionRequest.FromString,
                    response_serializer=rl_dot_proto_dot_minimetro__pb2.StepResponse.SerializeToString,
            ),
            'ResetVector': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetVector,
                    request_deserializer=rl_dot_proto_dot_minimetro__pb2.VectorResetRequest.FromString,
                    response_serializer=rl_dot_proto_dot_minimetro__pb2.VectorResetResponse.SerializeToString,
            ),
            'RunVectorEpisode': grpc.stream_stream_rpc_method_handler(
                    servicer.RunVectorEpisode,
                    request_deserializer=rl_dot_proto_dot_minimetro__pb2.VectorActionRequest.FromString,
                    response_serializer=rl_dot_proto_dot_minimetro__pb2.VectorStepResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rl.RLEnv', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rl.RLEnv', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RLEnv(object):
    """RLEnv exposes a single Mini Metro game instance for RL training.

    Typical usage per worker:
    1. Call Info() once at startup to validate constants.
    2. Call Reset() to begin an episode and receive the first observation.
    3. Open a RunEpisode stream: send ActionRequests, receive StepResponses
    until done=true.  Then call Reset() again for the next episode.
    """

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.RLEnv/Info',
            rl_dot_proto_dot_minimetro__pb2.Empty.SerializeToString,
            rl_dot_proto_dot_minimetro__pb2.InfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.RLEnv/Reset',
            rl_dot_proto_dot_minimetro__pb2.ResetRequest.SerializeToString,
            rl_dot_proto_dot_minimetro__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunEpisode(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/rl.RLEnv/RunEpisode',
            rl_dot_proto_dot_minimetro__pb2.ActionRequest.SerializeToString,
            rl_dot_proto_dot_minimetro__pb2.StepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.RLEnv/ResetVector',
            rl_dot_proto_dot_minimetro__pb2.VectorResetRequest.SerializeToString,
            rl_dot_proto_dot_minimetro__pb2.VectorResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunVectorEpisode(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/rl.RLEnv/RunVectorEpisode',
            rl_dot_proto_dot_minimetro__pb2.VectorActionRequest.SerializeToString,
            rl_dot_proto_dot_minimetro__pb2.VectorStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ControlStub(object):
    """Control exposes training-time knobs used by curriculum and evolutionary runs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetDifficulty = channel.unary_unary(
                '/rl.Control/SetDifficulty',
                request_serializer=rl_dot_proto_dot_minimetro__pb2.ResetRequest.SerializeToString,
                response_deserializer=rl_dot_proto_dot_minimetro__pb2.Empty.FromString,
                _registered_method=True)
        self.SetComplexity = channel.unary_unary(
                '/rl.Control/SetComplexity',
                request_serializer=rl_dot_proto_dot_minimetro__pb2.ResetRequest.SerializeToString,
                response_deserializer=rl_dot_proto_dot_minimetro__pb2.Empty.FromString,
                _registered_method=True)
        self.SetRewardConfig = channel.unary_unary(
                '/rl.Control/SetRewardConfig',
                request_serializer=rl_dot_proto_dot_minimetro__pb2.RewardConfigRequest.SerializeToString,
                response_deserializer=rl_dot_proto_dot_minimetro__pb2.Empty.FromString,
                _registered_method=True)


class ControlServicer(object):
    """Control exposes training-time knobs used by curriculum and evolutionary runs.
    """

    def SetDifficulty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetComplexity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRewardConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetDifficulty': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDifficulty,
                    request_deserializer=rl_dot_proto_dot_minimetro__pb2.ResetRequest.FromString,
                    response_serializer=rl_dot_proto_dot_minimetro__pb2.Empty.SerializeToString,
            ),
            'SetComplexity': grpc.unary_unary_rpc_method_handler(
                    servicer.SetComplexity,
                    request_deserializer=rl_dot_proto_dot_minimetro__pb2.ResetRequest.FromString,
                    response_serializer=rl_dot_proto_dot_minimetro__pb2.Empty.SerializeToString,
            ),
            'SetRewardConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRewardConfig,
                    request_deserializer=rl_dot_proto_dot_minimetro__pb2.RewardConfigRequest.FromString,
                    response_serializer=rl_dot_proto_dot_minimetro__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rl.Control', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rl.Control', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Control(object):
    """Control exposes training-time knobs used by curriculum and evolutionary runs.
    """

    @staticmethod
    def SetDifficulty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.Control/SetDifficulty',
            rl_dot_proto_dot_minimetro__pb2.ResetRequest.SerializeToString,
            rl_dot_proto_dot_minimetro__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetComplexity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.Control/SetComplexity',
            rl_dot_proto_dot_minimetro__pb2.ResetRequest.SerializeToString,
            rl_dot_proto_dot_minimetro__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRewardConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.Control/SetRewardConfig',
            rl_dot_proto_dot_minimetro__pb2.RewardConfigRequest.SerializeToString,
            rl_dot_proto_dot_minimetro__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class InferenceStub(object):
    """Inference is implemented by the Python inference server (infer.py).
    The Go live-game binary is the client (--rl-client flag).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Act = channel.unary_unary(
                '/rl.Inference/Act',
                request_serializer=rl_dot_proto_dot_minimetro__pb2.ActRequest.SerializeToString,
                response_deserializer=rl_dot_proto_dot_minimetro__pb2.ActionResponse.FromString,
                _registered_method=True)


class InferenceServicer(object):
    """Inference is implemented by the Python inference server (infer.py).
    The Go live-game binary is the client (--rl-client flag).
    """

    def Act(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Act': grpc.unary_unary_rpc_method_handler(
                    servicer.Act,
                    request_deserializer=rl_dot_proto_dot_minimetro__pb2.ActRequest.FromString,
                    response_serializer=rl_dot_proto_dot_minimetro__pb2.ActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rl.Inference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rl.Inference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Inference(object):
    """Inference is implemented by the Python inference server (infer.py).
    The Go live-game binary is the client (--rl-client flag).
    """

    @staticmethod
    def Act(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.Inference/Act',
            rl_dot_proto_dot_minimetro__pb2.ActRequest.SerializeToString,
            rl_dot_proto_dot_minimetro__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
