// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: rl/proto/minimetro.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_rl_proto_minimetro_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_rl_proto_minimetro_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_rl_proto_minimetro_proto_rawDescGZIP(), []int{0}
}

type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObsDim        int32                  `protobuf:"varint,1,opt,name=obs_dim,json=obsDim,proto3" json:"obs_dim,omitempty"`
	ActionDims    []int32                `protobuf:"varint,2,rep,packed,name=action_dims,json=actionDims,proto3" json:"action_dims,omitempty"`
	GlobalDim     int32                  `protobuf:"varint,3,opt,name=global_dim,json=globalDim,proto3" json:"global_dim,omitempty"`
	StationDim    int32                  `protobuf:"varint,4,opt,name=station_dim,json=stationDim,proto3" json:"station_dim,omitempty"`
	NumStations   int32                  `protobuf:"varint,5,opt,name=num_stations,json=numStations,proto3" json:"num_stations,omitempty"`
	LineDim       int32                  `protobuf:"varint,6,opt,name=line_dim,json=lineDim,proto3" json:"line_dim,omitempty"`
	NumLines      int32                  `protobuf:"varint,7,opt,name=num_lines,json=numLines,proto3" json:"num_lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_rl_proto_minimetro_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rl_proto_minimetro_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_rl_proto_minimetro_proto_rawDescGZIP(), []int{1}
}

func (x *InfoResponse) GetObsDim() int32 {
	if x != nil {
		return x.ObsDim
	}
	return 0
}

func (x *InfoResponse) GetActionDims() []int32 {
	if x != nil {
		return x.ActionDims
	}
	return nil
}

func (x *InfoResponse) GetGlobalDim() int32 {
	if x != nil {
		return x.GlobalDim
	}
	return 0
}

func (x *InfoResponse) GetStationDim() int32 {
	if x != nil {
		return x.StationDim
	}
	return 0
}

func (x *InfoResponse) GetNumStations() int32 {
	if x != nil {
		return x.NumStations
	}
	return 0
}

func (x *InfoResponse) GetLineDim() int32 {
	if x != nil {
		return x.LineDim
	}
	return 0
}

func (x *InfoResponse) GetNumLines() int32 {
	if x != nil {
		return x.NumLines
	}
	return 0
}

type ResetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	City  string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	// spawn_rate_factor scales the passenger and station spawn intervals.
	// Values > 1.0 slow spawning (easier); 1.0 = normal difficulty.
	// Used by curriculum learning: the Python side increases this at episode
	// reset when the agent has not yet mastered the current level.
	SpawnRateFactor float32 `protobuf:"fixed32,2,opt,name=spawn_rate_factor,json=spawnRateFactor,proto3" json:"spawn_rate_factor,omitempty"`
	// Optional deterministic episode seed. Zero keeps the server default.
	Seed          int64 `protobuf:"varint,3,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_rl_proto_minimetro_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rl_proto_minimetro_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_rl_proto_minimetro_proto_rawDescGZIP(), []int{2}
}

func (x *ResetRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ResetRequest) GetSpawnRateFactor() float32 {
	if x != nil {
		return x.SpawnRateFactor
	}
	return 0
}

func (x *ResetRequest) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

type ResetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Float32 observation vector of length obs_dim, packed.
	Obs []float32 `protobuf:"fixed32,1,rep,packed,name=obs,proto3" json:"obs,omitempty"`
	// Boolean action mask of length sum(action_dims), one bool per element.
	Mask          []bool `protobuf:"varint,2,rep,packed,name=mask,proto3" json:"mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_rl_proto_minimetro_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rl_proto_minimetro_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_rl_proto_minimetro_proto_rawDescGZIP(), []int{3}
}

func (x *ResetResponse) GetObs() []float32 {
	if x != nil {
		return x.Obs
	}
	return nil
}

func (x *ResetResponse) GetMask() []bool {
	if x != nil {
		return x.Mask
	}
	return nil
}

type VectorResetRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NumEnvs         int32                  `protobuf:"varint,1,opt,name=num_envs,json=numEnvs,proto3" json:"num_envs,omitempty"`
	City            string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	SpawnRateFactor float32                `protobuf:"fixed32,3,opt,name=spawn_rate_factor,json=spawnRateFactor,proto3" json:"spawn_rate_factor,omitempty"`
	// Optional deterministic base seed. Env i uses seed+i. Zero keeps defaults.
	Seed          int64 `protobuf:"varint,4,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorResetRequest) Reset() {
	*x = VectorResetRequest{}
	mi := &file_rl_proto_minimetro_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorResetRequest) ProtoMessage() {}

func (x *VectorResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rl_proto_minimetro_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorResetRequest.ProtoReflect.Descriptor instead.
func (*VectorResetRequest) Descriptor() ([]byte, []int) {
	return file_rl_proto_minimetro_proto_rawDescGZIP(), []int{4}
}

func (x *VectorResetRequest) GetNumEnvs() int32 {
	if x != nil {
		return x.NumEnvs
	}
	return 0
}

func (x *VectorResetRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *VectorResetRequest) GetSpawnRateFactor() float32 {
	if x != nil {
		return x.SpawnRateFactor
	}
	return 0
}

func (x *VectorResetRequest) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

type VectorResetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// obs length = num_envs * obs_dim
	Obs []float32 `protobuf:"fixed32,1,rep,packed,name=obs,proto3" json:"obs,omitempty"`
	// mask length = num_envs * sum(action_dims)
	Mask          []bool `protobuf:"varint,2,rep,packed,name=mask,proto3" json:"mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorResetResponse) Reset() {
	*x = VectorResetResponse{}
	mi := &file_rl_proto_minimetro_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorResetResponse) ProtoMessage() {}

func (x *VectorResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rl_proto_minimetro_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorResetResponse.ProtoReflect.Descriptor instead.
func (*VectorResetResponse) Descriptor() ([]byte, []int) {
	return file_rl_proto_minimetro_proto_rawDescGZIP(), []int{5}
}

func (x *VectorResetResponse) GetObs() []float32 {
	if x != nil {
		return x.Obs
	}
	return nil
}

func (x *VectorResetResponse) GetMask() []bool {
	if x != nil {
		return x.Mask
	}
	return nil
}

type RewardConfigRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PerPassenger        float64                `protobuf:"fixed64,1,opt,name=per_passenger,json=perPassenger,proto3" json:"per_passenger,omitempty"`
	QueueCoeff          float64                `protobuf:"fixed64,2,opt,name=queue_coeff,json=queueCoeff,proto3" json:"queue_coeff,omitempty"`
	QueueDeltaCoeff     float64                `protobuf:"fixed64,3,opt,name=queue_delta_coeff,json=queueDeltaCoeff,proto3" json:"queue_delta_coeff,omitempty"`
	OvercrowdCoeff      float64                `protobuf:"fixed64,4,opt,name=overcrowd_coeff,json=overcrowdCoeff,proto3" json:"overcrowd_coeff,omitempty"`
	OvercrowdDeltaCoeff float64                `protobuf:"fixed64,5,opt,name=overcrowd_delta_coeff,json=overcrowdDeltaCoeff,proto3" json:"overcrowd_delta_coeff,omitempty"`
	DangerThresh        float64                `protobuf:"fixed64,6,opt,name=danger_thresh,json=dangerThresh,proto3" json:"danger_thresh,omitempty"`
	DangerPenalty       float64                `protobuf:"fixed64,7,opt,name=danger_penalty,json=dangerPenalty,proto3" json:"danger_penalty,omitempty"`
	NoopCriticalPenalty float64                `protobuf:"fixed64,8,opt,name=noop_critical_penalty,json=noopCriticalPenalty,proto3" json:"noop_critical_penalty,omitempty"`
	WeekBonus           float64                `protobuf:"fixed64,9,opt,name=week_bonus,json=weekBonus,proto3" json:"week_bonus,omitempty"`
	TerminalPenalty     float64                `protobuf:"fixed64,10,opt,name=terminal_penalty,json=terminalPenalty,proto3" json:"terminal_penalty,omitempty"`
	InvalidAction       float64                `protobuf:"fixed64,11,opt,name=invalid_action,json=invalidAction,proto3" json:"invalid_action,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RewardConfigRequest) Reset() {
	*x = RewardConfigRequest{}
	mi := &file_rl_proto_minimetro_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewardConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewardConfigRequest) ProtoMessage() {}

func (x *RewardConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rl_proto_minimetro_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewardConfigRequest.ProtoReflect.Descriptor instead.
func (*RewardConfigRequest) Descriptor() ([]byte, []int) {
	return file_rl_proto_minimetro_proto_rawDescGZIP(), []int{6}
}

func (x *RewardConfigRequest) GetPerPassenger() float64 {
	if x != nil {
		return x.PerPassenger
	}
	return 0
}

func (x *RewardConfigRequest) GetQueueCoeff() float64 {
	if x != nil {
		return x.QueueCoeff
	}
	return 0
}

func (x *RewardConfigRequest) GetQueueDeltaCoeff() float64 {
	if x != nil {
		return x.QueueDeltaCoeff
	}
	return 0
}

func (x *RewardConfigRequest) GetOvercrowdCoeff() float64 {
	if x != nil {
		return x.OvercrowdCoeff
	}
	return 0
}

func (x *RewardConfigRequest) GetOvercrowdDeltaCoeff() float64 {
	if x != nil {
		return x.OvercrowdDeltaCoeff
	}
	return 0
}

func (x *RewardConfigRequest) GetDangerThresh() float64 {
	if x != nil {
		return x.DangerThresh
	}
	return 0
}

func (x *RewardConfigRequest) GetDangerPenalty() float64 {
	if x != nil {
		return x.DangerPenalty
	}
	return 0
}

func (x *RewardConfigRequest) GetNoopCriticalPenalty() float64 {
	if x != nil {
		return x.NoopCriticalPenalty
	}
	return 0
}

func (x *RewardConfigRequest) GetWeekBonus() float64 {
	if x != nil {
		return x.WeekBonus
	}
	return 0
}

func (x *RewardConfigRequest) GetTerminalPenalty() float64 {
	if x != nil {
		return x.TerminalPenalty
	}
	return 0
}

func (x *RewardConfigRequest) GetInvalidAction() float64 {
	if x != nil {
		return x.InvalidAction
	}
	return 0
}

type ActionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Four-element MultiDiscrete action: [act_cat, line_idx, station_idx, opt].
	Action        []int32 `protobuf:"varint,1,rep,packed,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionRequest) Reset() {
	*x = ActionRequest{}
	mi := &file_rl_proto_minimetro_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRequest) ProtoMessage() {}

func (x *ActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rl_proto_minimetro_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRequest.ProtoReflect.Descriptor instead.
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return file_rl_proto_minimetro_proto_rawDescGZIP(), []int{7}
}

func (x *ActionRequest) GetAction() []int32 {
	if x != nil {
		return x.Action
	}
	return nil
}

type StepResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Obs    []float32              `protobuf:"fixed32,1,rep,packed,name=obs,proto3" json:"obs,omitempty"`
	Mask   []bool                 `protobuf:"varint,2,rep,packed,name=mask,proto3" json:"mask,omitempty"`
	Reward float64                `protobuf:"fixed64,3,opt,name=reward,proto3" json:"reward,omitempty"`
	Done   bool                   `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`
	// Info fields (subset of the JSON /step info map).
	Score               int32 `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	PassengersDelivered int32 `protobuf:"varint,6,opt,name=passengers_delivered,json=passengersDelivered,proto3" json:"passengers_delivered,omitempty"`
	Week                int32 `protobuf:"varint,7,opt,name=week,proto3" json:"week,omitempty"`
	Stations            int32 `protobuf:"varint,8,opt,name=stations,proto3" json:"stations,omitempty"`
	GameOver            bool  `protobuf:"varint,9,opt,name=game_over,json=gameOver,proto3" json:"game_over,omitempty"`
	InUpgradeModal      bool  `protobuf:"varint,10,opt,name=in_upgrade_modal,json=inUpgradeModal,proto3" json:"in_upgrade_modal,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StepResponse) Reset() {
	*x = StepResponse{}
	mi := &file_rl_proto_minimetro_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResponse) ProtoMessage() {}

func (x *StepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rl_proto_minimetro_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResponse.ProtoReflect.Descriptor instead.
func (*StepResponse) Descriptor() ([]byte, []int) {
	return file_rl_proto_minimetro_proto_rawDescGZIP(), []int{8}
}

func (x *StepResponse) GetObs() []float32 {
	if x != nil {
		return x.Obs
	}
	return nil
}

func (x *StepResponse) GetMask() []bool {
	if x != nil {
		return x.Mask
	}
	return nil
}

func (x *StepResponse) GetReward() float64 {
	if x != nil {
		return x.Reward
	}
	return 0
}

func (x *StepResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *StepResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *StepResponse) GetPassengersDelivered() int32 {
	if x != nil {
		return x.PassengersDelivered
	}
	return 0
}

func (x *StepResponse) GetWeek() int32 {
	if x != nil {
		return x.Week
	}
	return 0
}

func (x *StepResponse) GetStations() int32 {
	if x != nil {
		return x.Stations
	}
	return 0
}

func (x *StepResponse) GetGameOver() bool {
	if x != nil {
		return x.GameOver
	}
	return false
}

func (x *StepResponse) GetInUpgradeModal() bool {
	if x != nil {
		return x.InUpgradeModal
	}
	return false
}

type VectorActionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// length = num_envs * 4
	Actions       []int32 `protobuf:"varint,1,rep,packed,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorActionRequest) Reset() {
	*x = VectorActionRequest{}
	mi := &file_rl_proto_minimetro_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorActionRequest) ProtoMessage() {}

func (x *VectorActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rl_proto_minimetro_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorActionRequest.ProtoReflect.Descriptor instead.
func (*VectorActionRequest) Descriptor() ([]byte, []int) {
	return file_rl_proto_minimetro_proto_rawDescGZIP(), []int{9}
}

func (x *VectorActionRequest) GetActions() []int32 {
	if x != nil {
		return x.Actions
	}
	return nil
}

type VectorStepResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All vectors are packed and map to the N environments.
	Obs    []float32 `protobuf:"fixed32,1,rep,packed,name=obs,proto3" json:"obs,omitempty"`       // length = N * obs_dim
	Mask   []bool    `protobuf:"varint,2,rep,packed,name=mask,proto3" json:"mask,omitempty"`      // length = N * sum(action_dims)
	Reward []float64 `protobuf:"fixed64,3,rep,packed,name=reward,proto3" json:"reward,omitempty"` // length = N
	Done   []bool    `protobuf:"varint,4,rep,packed,name=done,proto3" json:"done,omitempty"`      // length = N
	// SB3 requires the terminal observation when returning an auto-reset obs.
	// When done[i] is true, terminal_obs contains the ending game state.
	// Otherwise, its values are arbitrary (usually 0).
	TerminalObs []float32 `protobuf:"fixed32,5,rep,packed,name=terminal_obs,json=terminalObs,proto3" json:"terminal_obs,omitempty"` // length = N * obs_dim
	// Info fields
	Score               []int32 `protobuf:"varint,6,rep,packed,name=score,proto3" json:"score,omitempty"`
	PassengersDelivered []int32 `protobuf:"varint,7,rep,packed,name=passengers_delivered,json=passengersDelivered,proto3" json:"passengers_delivered,omitempty"`
	Week                []int32 `protobuf:"varint,8,rep,packed,name=week,proto3" json:"week,omitempty"`
	Stations            []int32 `protobuf:"varint,9,rep,packed,name=stations,proto3" json:"stations,omitempty"`
	GameOver            []bool  `protobuf:"varint,10,rep,packed,name=game_over,json=gameOver,proto3" json:"game_over,omitempty"`
	InUpgradeModal      []bool  `protobuf:"varint,11,rep,packed,name=in_upgrade_modal,json=inUpgradeModal,proto3" json:"in_upgrade_modal,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *VectorStepResponse) Reset() {
	*x = VectorStepResponse{}
	mi := &file_rl_proto_minimetro_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorStepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorStepResponse) ProtoMessage() {}

func (x *VectorStepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rl_proto_minimetro_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorStepResponse.ProtoReflect.Descriptor instead.
func (*VectorStepResponse) Descriptor() ([]byte, []int) {
	return file_rl_proto_minimetro_proto_rawDescGZIP(), []int{10}
}

func (x *VectorStepResponse) GetObs() []float32 {
	if x != nil {
		return x.Obs
	}
	return nil
}

func (x *VectorStepResponse) GetMask() []bool {
	if x != nil {
		return x.Mask
	}
	return nil
}

func (x *VectorStepResponse) GetReward() []float64 {
	if x != nil {
		return x.Reward
	}
	return nil
}

func (x *VectorStepResponse) GetDone() []bool {
	if x != nil {
		return x.Done
	}
	return nil
}

func (x *VectorStepResponse) GetTerminalObs() []float32 {
	if x != nil {
		return x.TerminalObs
	}
	return nil
}

func (x *VectorStepResponse) GetScore() []int32 {
	if x != nil {
		return x.Score
	}
	return nil
}

func (x *VectorStepResponse) GetPassengersDelivered() []int32 {
	if x != nil {
		return x.PassengersDelivered
	}
	return nil
}

func (x *VectorStepResponse) GetWeek() []int32 {
	if x != nil {
		return x.Week
	}
	return nil
}

func (x *VectorStepResponse) GetStations() []int32 {
	if x != nil {
		return x.Stations
	}
	return nil
}

func (x *VectorStepResponse) GetGameOver() []bool {
	if x != nil {
		return x.GameOver
	}
	return nil
}

func (x *VectorStepResponse) GetInUpgradeModal() []bool {
	if x != nil {
		return x.InUpgradeModal
	}
	return nil
}

type ActRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Obs           []float32              `protobuf:"fixed32,1,rep,packed,name=obs,proto3" json:"obs,omitempty"`
	Mask          []bool                 `protobuf:"varint,2,rep,packed,name=mask,proto3" json:"mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActRequest) Reset() {
	*x = ActRequest{}
	mi := &file_rl_proto_minimetro_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActRequest) ProtoMessage() {}

func (x *ActRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rl_proto_minimetro_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActRequest.ProtoReflect.Descriptor instead.
func (*ActRequest) Descriptor() ([]byte, []int) {
	return file_rl_proto_minimetro_proto_rawDescGZIP(), []int{11}
}

func (x *ActRequest) GetObs() []float32 {
	if x != nil {
		return x.Obs
	}
	return nil
}

func (x *ActRequest) GetMask() []bool {
	if x != nil {
		return x.Mask
	}
	return nil
}

type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        []int32                `protobuf:"varint,1,rep,packed,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_rl_proto_minimetro_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rl_proto_minimetro_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_rl_proto_minimetro_proto_rawDescGZIP(), []int{12}
}

func (x *ActionResponse) GetAction() []int32 {
	if x != nil {
		return x.Action
	}
	return nil
}

var File_rl_proto_minimetro_proto protoreflect.FileDescriptor

const file_rl_proto_minimetro_proto_rawDesc = "" +
	"\n" +
	"\x18rl/proto/minimetro.proto\x12\x02rl\"\a\n" +
	"\x05Empty\"\xe3\x01\n" +
	"\fInfoResponse\x12\x17\n" +
	"\aobs_dim\x18\x01 \x01(\x05R\x06obsDim\x12\x1f\n" +
	"\vaction_dims\x18\x02 \x03(\x05R\n" +
	"actionDims\x12\x1d\n" +
	"\n" +
	"global_dim\x18\x03 \x01(\x05R\tglobalDim\x12\x1f\n" +
	"\vstation_dim\x18\x04 \x01(\x05R\n" +
	"stationDim\x12!\n" +
	"\fnum_stations\x18\x05 \x01(\x05R\vnumStations\x12\x19\n" +
	"\bline_dim\x18\x06 \x01(\x05R\alineDim\x12\x1b\n" +
	"\tnum_lines\x18\a \x01(\x05R\bnumLines\"b\n" +
	"\fResetRequest\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12*\n" +
	"\x11spawn_rate_factor\x18\x02 \x01(\x02R\x0fspawnRateFactor\x12\x12\n" +
	"\x04seed\x18\x03 \x01(\x03R\x04seed\"=\n" +
	"\rResetResponse\x12\x14\n" +
	"\x03obs\x18\x01 \x03(\x02B\x02\x10\x01R\x03obs\x12\x16\n" +
	"\x04mask\x18\x02 \x03(\bB\x02\x10\x01R\x04mask\"\x83\x01\n" +
	"\x12VectorResetRequest\x12\x19\n" +
	"\bnum_envs\x18\x01 \x01(\x05R\anumEnvs\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12*\n" +
	"\x11spawn_rate_factor\x18\x03 \x01(\x02R\x0fspawnRateFactor\x12\x12\n" +
	"\x04seed\x18\x04 \x01(\x03R\x04seed\"C\n" +
	"\x13VectorResetResponse\x12\x14\n" +
	"\x03obs\x18\x01 \x03(\x02B\x02\x10\x01R\x03obs\x12\x16\n" +
	"\x04mask\x18\x02 \x03(\bB\x02\x10\x01R\x04mask\"\xd5\x03\n" +
	"\x13RewardConfigRequest\x12#\n" +
	"\rper_passenger\x18\x01 \x01(\x01R\fperPassenger\x12\x1f\n" +
	"\vqueue_coeff\x18\x02 \x01(\x01R\n" +
	"queueCoeff\x12*\n" +
	"\x11queue_delta_coeff\x18\x03 \x01(\x01R\x0fqueueDeltaCoeff\x12'\n" +
	"\x0fovercrowd_coeff\x18\x04 \x01(\x01R\x0eovercrowdCoeff\x122\n" +
	"\x15overcrowd_delta_coeff\x18\x05 \x01(\x01R\x13overcrowdDeltaCoeff\x12#\n" +
	"\rdanger_thresh\x18\x06 \x01(\x01R\fdangerThresh\x12%\n" +
	"\x0edanger_penalty\x18\a \x01(\x01R\rdangerPenalty\x122\n" +
	"\x15noop_critical_penalty\x18\b \x01(\x01R\x13noopCriticalPenalty\x12\x1d\n" +
	"\n" +
	"week_bonus\x18\t \x01(\x01R\tweekBonus\x12)\n" +
	"\x10terminal_penalty\x18\n" +
	" \x01(\x01R\x0fterminalPenalty\x12%\n" +
	"\x0einvalid_action\x18\v \x01(\x01R\rinvalidAction\"+\n" +
	"\rActionRequest\x12\x1a\n" +
	"\x06action\x18\x01 \x03(\x05B\x02\x10\x01R\x06action\"\xa8\x02\n" +
	"\fStepResponse\x12\x14\n" +
	"\x03obs\x18\x01 \x03(\x02B\x02\x10\x01R\x03obs\x12\x16\n" +
	"\x04mask\x18\x02 \x03(\bB\x02\x10\x01R\x04mask\x12\x16\n" +
	"\x06reward\x18\x03 \x01(\x01R\x06reward\x12\x12\n" +
	"\x04done\x18\x04 \x01(\bR\x04done\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x05R\x05score\x121\n" +
	"\x14passengers_delivered\x18\x06 \x01(\x05R\x13passengersDelivered\x12\x12\n" +
	"\x04week\x18\a \x01(\x05R\x04week\x12\x1a\n" +
	"\bstations\x18\b \x01(\x05R\bstations\x12\x1b\n" +
	"\tgame_over\x18\t \x01(\bR\bgameOver\x12(\n" +
	"\x10in_upgrade_modal\x18\n" +
	" \x01(\bR\x0einUpgradeModal\"3\n" +
	"\x13VectorActionRequest\x12\x1c\n" +
	"\aactions\x18\x01 \x03(\x05B\x02\x10\x01R\aactions\"\xf5\x02\n" +
	"\x12VectorStepResponse\x12\x14\n" +
	"\x03obs\x18\x01 \x03(\x02B\x02\x10\x01R\x03obs\x12\x16\n" +
	"\x04mask\x18\x02 \x03(\bB\x02\x10\x01R\x04mask\x12\x1a\n" +
	"\x06reward\x18\x03 \x03(\x01B\x02\x10\x01R\x06reward\x12\x16\n" +
	"\x04done\x18\x04 \x03(\bB\x02\x10\x01R\x04done\x12%\n" +
	"\fterminal_obs\x18\x05 \x03(\x02B\x02\x10\x01R\vterminalObs\x12\x18\n" +
	"\x05score\x18\x06 \x03(\x05B\x02\x10\x01R\x05score\x125\n" +
	"\x14passengers_delivered\x18\a \x03(\x05B\x02\x10\x01R\x13passengersDelivered\x12\x16\n" +
	"\x04week\x18\b \x03(\x05B\x02\x10\x01R\x04week\x12\x1e\n" +
	"\bstations\x18\t \x03(\x05B\x02\x10\x01R\bstations\x12\x1f\n" +
	"\tgame_over\x18\n" +
	" \x03(\bB\x02\x10\x01R\bgameOver\x12,\n" +
	"\x10in_upgrade_modal\x18\v \x03(\bB\x02\x10\x01R\x0einUpgradeModal\":\n" +
	"\n" +
	"ActRequest\x12\x14\n" +
	"\x03obs\x18\x01 \x03(\x02B\x02\x10\x01R\x03obs\x12\x16\n" +
	"\x04mask\x18\x02 \x03(\bB\x02\x10\x01R\x04mask\",\n" +
	"\x0eActionResponse\x12\x1a\n" +
	"\x06action\x18\x01 \x03(\x05B\x02\x10\x01R\x06action2\xa4\x02\n" +
	"\x05RLEnv\x12%\n" +
	"\x04Info\x12\t.rl.Empty\x1a\x10.rl.InfoResponse\"\x00\x12.\n" +
	"\x05Reset\x12\x10.rl.ResetRequest\x1a\x11.rl.ResetResponse\"\x00\x127\n" +
	"\n" +
	"RunEpisode\x12\x11.rl.ActionRequest\x1a\x10.rl.StepResponse\"\x00(\x010\x01\x12@\n" +
	"\vResetVector\x12\x16.rl.VectorResetRequest\x1a\x17.rl.VectorResetResponse\"\x00\x12I\n" +
	"\x10RunVectorEpisode\x12\x17.rl.VectorActionRequest\x1a\x16.rl.VectorStepResponse\"\x00(\x010\x012\xa2\x01\n" +
	"\aControl\x12.\n" +
	"\rSetDifficulty\x12\x10.rl.ResetRequest\x1a\t.rl.Empty\"\x00\x12.\n" +
	"\rSetComplexity\x12\x10.rl.ResetRequest\x1a\t.rl.Empty\"\x00\x127\n" +
	"\x0fSetRewardConfig\x12\x17.rl.RewardConfigRequest\x1a\t.rl.Empty\"\x0028\n" +
	"\tInference\x12+\n" +
	"\x03Act\x12\x0e.rl.ActRequest\x1a\x12.rl.ActionResponse\"\x00B\x17Z\x15minimetro-go/rl/protob\x06proto3"

var (
	file_rl_proto_minimetro_proto_rawDescOnce sync.Once
	file_rl_proto_minimetro_proto_rawDescData []byte
)

func file_rl_proto_minimetro_proto_rawDescGZIP() []byte {
	file_rl_proto_minimetro_proto_rawDescOnce.Do(func() {
		file_rl_proto_minimetro_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rl_proto_minimetro_proto_rawDesc), len(file_rl_proto_minimetro_proto_rawDesc)))
	})
	return file_rl_proto_minimetro_proto_rawDescData
}

var file_rl_proto_minimetro_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_rl_proto_minimetro_proto_goTypes = []any{
	(*Empty)(nil),               // 0: rl.Empty
	(*InfoResponse)(nil),        // 1: rl.InfoResponse
	(*ResetRequest)(nil),        // 2: rl.ResetRequest
	(*ResetResponse)(nil),       // 3: rl.ResetResponse
	(*VectorResetRequest)(nil),  // 4: rl.VectorResetRequest
	(*VectorResetResponse)(nil), // 5: rl.VectorResetResponse
	(*RewardConfigRequest)(nil), // 6: rl.RewardConfigRequest
	(*ActionRequest)(nil),       // 7: rl.ActionRequest
	(*StepResponse)(nil),        // 8: rl.StepResponse
	(*VectorActionRequest)(nil), // 9: rl.VectorActionRequest
	(*VectorStepResponse)(nil),  // 10: rl.VectorStepResponse
	(*ActRequest)(nil),          // 11: rl.ActRequest
	(*ActionResponse)(nil),      // 12: rl.ActionResponse
}
var file_rl_proto_minimetro_proto_depIdxs = []int32{
	0,  // 0: rl.RLEnv.Info:input_type -> rl.Empty
	2,  // 1: rl.RLEnv.Reset:input_type -> rl.ResetRequest
	7,  // 2: rl.RLEnv.RunEpisode:input_type -> rl.ActionRequest
	4,  // 3: rl.RLEnv.ResetVector:input_type -> rl.VectorResetRequest
	9,  // 4: rl.RLEnv.RunVectorEpisode:input_type -> rl.VectorActionRequest
	2,  // 5: rl.Control.SetDifficulty:input_type -> rl.ResetRequest
	2,  // 6: rl.Control.SetComplexity:input_type -> rl.ResetRequest
	6,  // 7: rl.Control.SetRewardConfig:input_type -> rl.RewardConfigRequest
	11, // 8: rl.Inference.Act:input_type -> rl.ActRequest
	1,  // 9: rl.RLEnv.Info:output_type -> rl.InfoResponse
	3,  // 10: rl.RLEnv.Reset:output_type -> rl.ResetResponse
	8,  // 11: rl.RLEnv.RunEpisode:output_type -> rl.StepResponse
	5,  // 12: rl.RLEnv.ResetVector:output_type -> rl.VectorResetResponse
	10, // 13: rl.RLEnv.RunVectorEpisode:output_type -> rl.VectorStepResponse
	0,  // 14: rl.Control.SetDifficulty:output_type -> rl.Empty
	0,  // 15: rl.Control.SetComplexity:output_type -> rl.Empty
	0,  // 16: rl.Control.SetRewardConfig:output_type -> rl.Empty
	12, // 17: rl.Inference.Act:output_type -> rl.ActionResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_rl_proto_minimetro_proto_init() }
func file_rl_proto_minimetro_proto_init() {
	if File_rl_proto_minimetro_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rl_proto_minimetro_proto_rawDesc), len(file_rl_proto_minimetro_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_rl_proto_minimetro_proto_goTypes,
		DependencyIndexes: file_rl_proto_minimetro_proto_depIdxs,
		MessageInfos:      file_rl_proto_minimetro_proto_msgTypes,
	}.Build()
	File_rl_proto_minimetro_proto = out.File
	file_rl_proto_minimetro_proto_goTypes = nil
	file_rl_proto_minimetro_proto_depIdxs = nil
}
