// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: rl/proto/minimetro.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_rl_proto_minimetro_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_rl_proto_minimetro_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_rl_proto_minimetro_proto_rawDescGZIP(), []int{0}
}

type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObsDim        int32                  `protobuf:"varint,1,opt,name=obs_dim,json=obsDim,proto3" json:"obs_dim,omitempty"`
	ActionDims    []int32                `protobuf:"varint,2,rep,packed,name=action_dims,json=actionDims,proto3" json:"action_dims,omitempty"`
	GlobalDim     int32                  `protobuf:"varint,3,opt,name=global_dim,json=globalDim,proto3" json:"global_dim,omitempty"`
	StationDim    int32                  `protobuf:"varint,4,opt,name=station_dim,json=stationDim,proto3" json:"station_dim,omitempty"`
	NumStations   int32                  `protobuf:"varint,5,opt,name=num_stations,json=numStations,proto3" json:"num_stations,omitempty"`
	LineDim       int32                  `protobuf:"varint,6,opt,name=line_dim,json=lineDim,proto3" json:"line_dim,omitempty"`
	NumLines      int32                  `protobuf:"varint,7,opt,name=num_lines,json=numLines,proto3" json:"num_lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_rl_proto_minimetro_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rl_proto_minimetro_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_rl_proto_minimetro_proto_rawDescGZIP(), []int{1}
}

func (x *InfoResponse) GetObsDim() int32 {
	if x != nil {
		return x.ObsDim
	}
	return 0
}

func (x *InfoResponse) GetActionDims() []int32 {
	if x != nil {
		return x.ActionDims
	}
	return nil
}

func (x *InfoResponse) GetGlobalDim() int32 {
	if x != nil {
		return x.GlobalDim
	}
	return 0
}

func (x *InfoResponse) GetStationDim() int32 {
	if x != nil {
		return x.StationDim
	}
	return 0
}

func (x *InfoResponse) GetNumStations() int32 {
	if x != nil {
		return x.NumStations
	}
	return 0
}

func (x *InfoResponse) GetLineDim() int32 {
	if x != nil {
		return x.LineDim
	}
	return 0
}

func (x *InfoResponse) GetNumLines() int32 {
	if x != nil {
		return x.NumLines
	}
	return 0
}

type ResetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	City  string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	// spawn_rate_factor scales the passenger and station spawn intervals.
	// Values > 1.0 slow spawning (easier); 1.0 = normal difficulty.
	// Used by curriculum learning: the Python side increases this at episode
	// reset when the agent has not yet mastered the current level.
	SpawnRateFactor float32 `protobuf:"fixed32,2,opt,name=spawn_rate_factor,json=spawnRateFactor,proto3" json:"spawn_rate_factor,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_rl_proto_minimetro_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rl_proto_minimetro_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_rl_proto_minimetro_proto_rawDescGZIP(), []int{2}
}

func (x *ResetRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ResetRequest) GetSpawnRateFactor() float32 {
	if x != nil {
		return x.SpawnRateFactor
	}
	return 0
}

type ResetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Float32 observation vector of length obs_dim, packed.
	Obs []float32 `protobuf:"fixed32,1,rep,packed,name=obs,proto3" json:"obs,omitempty"`
	// Boolean action mask of length sum(action_dims), one bool per element.
	Mask          []bool `protobuf:"varint,2,rep,packed,name=mask,proto3" json:"mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_rl_proto_minimetro_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rl_proto_minimetro_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_rl_proto_minimetro_proto_rawDescGZIP(), []int{3}
}

func (x *ResetResponse) GetObs() []float32 {
	if x != nil {
		return x.Obs
	}
	return nil
}

func (x *ResetResponse) GetMask() []bool {
	if x != nil {
		return x.Mask
	}
	return nil
}

type ActionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Four-element MultiDiscrete action: [act_cat, line_idx, station_idx, opt].
	Action        []int32 `protobuf:"varint,1,rep,packed,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionRequest) Reset() {
	*x = ActionRequest{}
	mi := &file_rl_proto_minimetro_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRequest) ProtoMessage() {}

func (x *ActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rl_proto_minimetro_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRequest.ProtoReflect.Descriptor instead.
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return file_rl_proto_minimetro_proto_rawDescGZIP(), []int{4}
}

func (x *ActionRequest) GetAction() []int32 {
	if x != nil {
		return x.Action
	}
	return nil
}

type StepResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Obs    []float32              `protobuf:"fixed32,1,rep,packed,name=obs,proto3" json:"obs,omitempty"`
	Mask   []bool                 `protobuf:"varint,2,rep,packed,name=mask,proto3" json:"mask,omitempty"`
	Reward float64                `protobuf:"fixed64,3,opt,name=reward,proto3" json:"reward,omitempty"`
	Done   bool                   `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`
	// Info fields (subset of the JSON /step info map).
	Score               int32 `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	PassengersDelivered int32 `protobuf:"varint,6,opt,name=passengers_delivered,json=passengersDelivered,proto3" json:"passengers_delivered,omitempty"`
	Week                int32 `protobuf:"varint,7,opt,name=week,proto3" json:"week,omitempty"`
	Stations            int32 `protobuf:"varint,8,opt,name=stations,proto3" json:"stations,omitempty"`
	GameOver            bool  `protobuf:"varint,9,opt,name=game_over,json=gameOver,proto3" json:"game_over,omitempty"`
	InUpgradeModal      bool  `protobuf:"varint,10,opt,name=in_upgrade_modal,json=inUpgradeModal,proto3" json:"in_upgrade_modal,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StepResponse) Reset() {
	*x = StepResponse{}
	mi := &file_rl_proto_minimetro_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResponse) ProtoMessage() {}

func (x *StepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rl_proto_minimetro_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResponse.ProtoReflect.Descriptor instead.
func (*StepResponse) Descriptor() ([]byte, []int) {
	return file_rl_proto_minimetro_proto_rawDescGZIP(), []int{5}
}

func (x *StepResponse) GetObs() []float32 {
	if x != nil {
		return x.Obs
	}
	return nil
}

func (x *StepResponse) GetMask() []bool {
	if x != nil {
		return x.Mask
	}
	return nil
}

func (x *StepResponse) GetReward() float64 {
	if x != nil {
		return x.Reward
	}
	return 0
}

func (x *StepResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *StepResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *StepResponse) GetPassengersDelivered() int32 {
	if x != nil {
		return x.PassengersDelivered
	}
	return 0
}

func (x *StepResponse) GetWeek() int32 {
	if x != nil {
		return x.Week
	}
	return 0
}

func (x *StepResponse) GetStations() int32 {
	if x != nil {
		return x.Stations
	}
	return 0
}

func (x *StepResponse) GetGameOver() bool {
	if x != nil {
		return x.GameOver
	}
	return false
}

func (x *StepResponse) GetInUpgradeModal() bool {
	if x != nil {
		return x.InUpgradeModal
	}
	return false
}

type ActRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Obs           []float32              `protobuf:"fixed32,1,rep,packed,name=obs,proto3" json:"obs,omitempty"`
	Mask          []bool                 `protobuf:"varint,2,rep,packed,name=mask,proto3" json:"mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActRequest) Reset() {
	*x = ActRequest{}
	mi := &file_rl_proto_minimetro_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActRequest) ProtoMessage() {}

func (x *ActRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rl_proto_minimetro_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActRequest.ProtoReflect.Descriptor instead.
func (*ActRequest) Descriptor() ([]byte, []int) {
	return file_rl_proto_minimetro_proto_rawDescGZIP(), []int{6}
}

func (x *ActRequest) GetObs() []float32 {
	if x != nil {
		return x.Obs
	}
	return nil
}

func (x *ActRequest) GetMask() []bool {
	if x != nil {
		return x.Mask
	}
	return nil
}

type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        []int32                `protobuf:"varint,1,rep,packed,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_rl_proto_minimetro_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rl_proto_minimetro_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_rl_proto_minimetro_proto_rawDescGZIP(), []int{7}
}

func (x *ActionResponse) GetAction() []int32 {
	if x != nil {
		return x.Action
	}
	return nil
}

var File_rl_proto_minimetro_proto protoreflect.FileDescriptor

const file_rl_proto_minimetro_proto_rawDesc = "" +
	"\n" +
	"\x18rl/proto/minimetro.proto\x12\x02rl\"\a\n" +
	"\x05Empty\"\xe3\x01\n" +
	"\fInfoResponse\x12\x17\n" +
	"\aobs_dim\x18\x01 \x01(\x05R\x06obsDim\x12\x1f\n" +
	"\vaction_dims\x18\x02 \x03(\x05R\n" +
	"actionDims\x12\x1d\n" +
	"\n" +
	"global_dim\x18\x03 \x01(\x05R\tglobalDim\x12\x1f\n" +
	"\vstation_dim\x18\x04 \x01(\x05R\n" +
	"stationDim\x12!\n" +
	"\fnum_stations\x18\x05 \x01(\x05R\vnumStations\x12\x19\n" +
	"\bline_dim\x18\x06 \x01(\x05R\alineDim\x12\x1b\n" +
	"\tnum_lines\x18\a \x01(\x05R\bnumLines\"N\n" +
	"\fResetRequest\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12*\n" +
	"\x11spawn_rate_factor\x18\x02 \x01(\x02R\x0fspawnRateFactor\"=\n" +
	"\rResetResponse\x12\x14\n" +
	"\x03obs\x18\x01 \x03(\x02B\x02\x10\x01R\x03obs\x12\x16\n" +
	"\x04mask\x18\x02 \x03(\bB\x02\x10\x01R\x04mask\"+\n" +
	"\rActionRequest\x12\x1a\n" +
	"\x06action\x18\x01 \x03(\x05B\x02\x10\x01R\x06action\"\xa8\x02\n" +
	"\fStepResponse\x12\x14\n" +
	"\x03obs\x18\x01 \x03(\x02B\x02\x10\x01R\x03obs\x12\x16\n" +
	"\x04mask\x18\x02 \x03(\bB\x02\x10\x01R\x04mask\x12\x16\n" +
	"\x06reward\x18\x03 \x01(\x01R\x06reward\x12\x12\n" +
	"\x04done\x18\x04 \x01(\bR\x04done\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x05R\x05score\x121\n" +
	"\x14passengers_delivered\x18\x06 \x01(\x05R\x13passengersDelivered\x12\x12\n" +
	"\x04week\x18\a \x01(\x05R\x04week\x12\x1a\n" +
	"\bstations\x18\b \x01(\x05R\bstations\x12\x1b\n" +
	"\tgame_over\x18\t \x01(\bR\bgameOver\x12(\n" +
	"\x10in_upgrade_modal\x18\n" +
	" \x01(\bR\x0einUpgradeModal\":\n" +
	"\n" +
	"ActRequest\x12\x14\n" +
	"\x03obs\x18\x01 \x03(\x02B\x02\x10\x01R\x03obs\x12\x16\n" +
	"\x04mask\x18\x02 \x03(\bB\x02\x10\x01R\x04mask\",\n" +
	"\x0eActionResponse\x12\x1a\n" +
	"\x06action\x18\x01 \x03(\x05B\x02\x10\x01R\x06action2\x97\x01\n" +
	"\x05RLEnv\x12%\n" +
	"\x04Info\x12\t.rl.Empty\x1a\x10.rl.InfoResponse\"\x00\x12.\n" +
	"\x05Reset\x12\x10.rl.ResetRequest\x1a\x11.rl.ResetResponse\"\x00\x127\n" +
	"\n" +
	"RunEpisode\x12\x11.rl.ActionRequest\x1a\x10.rl.StepResponse\"\x00(\x010\x0128\n" +
	"\tInference\x12+\n" +
	"\x03Act\x12\x0e.rl.ActRequest\x1a\x12.rl.ActionResponse\"\x00B\x17Z\x15minimetro-go/rl/protob\x06proto3"

var (
	file_rl_proto_minimetro_proto_rawDescOnce sync.Once
	file_rl_proto_minimetro_proto_rawDescData []byte
)

func file_rl_proto_minimetro_proto_rawDescGZIP() []byte {
	file_rl_proto_minimetro_proto_rawDescOnce.Do(func() {
		file_rl_proto_minimetro_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rl_proto_minimetro_proto_rawDesc), len(file_rl_proto_minimetro_proto_rawDesc)))
	})
	return file_rl_proto_minimetro_proto_rawDescData
}

var file_rl_proto_minimetro_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_rl_proto_minimetro_proto_goTypes = []any{
	(*Empty)(nil),          // 0: rl.Empty
	(*InfoResponse)(nil),   // 1: rl.InfoResponse
	(*ResetRequest)(nil),   // 2: rl.ResetRequest
	(*ResetResponse)(nil),  // 3: rl.ResetResponse
	(*ActionRequest)(nil),  // 4: rl.ActionRequest
	(*StepResponse)(nil),   // 5: rl.StepResponse
	(*ActRequest)(nil),     // 6: rl.ActRequest
	(*ActionResponse)(nil), // 7: rl.ActionResponse
}
var file_rl_proto_minimetro_proto_depIdxs = []int32{
	0, // 0: rl.RLEnv.Info:input_type -> rl.Empty
	2, // 1: rl.RLEnv.Reset:input_type -> rl.ResetRequest
	4, // 2: rl.RLEnv.RunEpisode:input_type -> rl.ActionRequest
	6, // 3: rl.Inference.Act:input_type -> rl.ActRequest
	1, // 4: rl.RLEnv.Info:output_type -> rl.InfoResponse
	3, // 5: rl.RLEnv.Reset:output_type -> rl.ResetResponse
	5, // 6: rl.RLEnv.RunEpisode:output_type -> rl.StepResponse
	7, // 7: rl.Inference.Act:output_type -> rl.ActionResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rl_proto_minimetro_proto_init() }
func file_rl_proto_minimetro_proto_init() {
	if File_rl_proto_minimetro_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rl_proto_minimetro_proto_rawDesc), len(file_rl_proto_minimetro_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_rl_proto_minimetro_proto_goTypes,
		DependencyIndexes: file_rl_proto_minimetro_proto_depIdxs,
		MessageInfos:      file_rl_proto_minimetro_proto_msgTypes,
	}.Build()
	File_rl_proto_minimetro_proto = out.File
	file_rl_proto_minimetro_proto_goTypes = nil
	file_rl_proto_minimetro_proto_depIdxs = nil
}
