// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: rl/proto/minimetro.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RLEnv_Info_FullMethodName             = "/rl.RLEnv/Info"
	RLEnv_Reset_FullMethodName            = "/rl.RLEnv/Reset"
	RLEnv_RunEpisode_FullMethodName       = "/rl.RLEnv/RunEpisode"
	RLEnv_ResetVector_FullMethodName      = "/rl.RLEnv/ResetVector"
	RLEnv_RunVectorEpisode_FullMethodName = "/rl.RLEnv/RunVectorEpisode"
)

// RLEnvClient is the client API for RLEnv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RLEnv exposes a single Mini Metro game instance for RL training.
//
// Typical usage per worker:
//  1. Call Info() once at startup to validate constants.
//  2. Call Reset() to begin an episode and receive the first observation.
//  3. Open a RunEpisode stream: send ActionRequests, receive StepResponses
//     until done=true.  Then call Reset() again for the next episode.
type RLEnvClient interface {
	// Info returns environment constants for startup validation.
	Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InfoResponse, error)
	// Reset starts a new episode and returns the initial observation.
	Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error)
	// RunEpisode is a bidirectional stream for the inner training loop.
	// The client sends one ActionRequest per step; the server replies with
	// one StepResponse.  The stream stays open across steps within one episode.
	// When done=true in a StepResponse, call Reset() to begin the next episode
	// (the stream can be reused — send the next action after Reset returns).
	RunEpisode(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ActionRequest, StepResponse], error)
	// Vectorized endpoints for scaling throughput.
	ResetVector(ctx context.Context, in *VectorResetRequest, opts ...grpc.CallOption) (*VectorResetResponse, error)
	RunVectorEpisode(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[VectorActionRequest, VectorStepResponse], error)
}

type rLEnvClient struct {
	cc grpc.ClientConnInterface
}

func NewRLEnvClient(cc grpc.ClientConnInterface) RLEnvClient {
	return &rLEnvClient{cc}
}

func (c *rLEnvClient) Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, RLEnv_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rLEnvClient) Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetResponse)
	err := c.cc.Invoke(ctx, RLEnv_Reset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rLEnvClient) RunEpisode(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ActionRequest, StepResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RLEnv_ServiceDesc.Streams[0], RLEnv_RunEpisode_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ActionRequest, StepResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RLEnv_RunEpisodeClient = grpc.BidiStreamingClient[ActionRequest, StepResponse]

func (c *rLEnvClient) ResetVector(ctx context.Context, in *VectorResetRequest, opts ...grpc.CallOption) (*VectorResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VectorResetResponse)
	err := c.cc.Invoke(ctx, RLEnv_ResetVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rLEnvClient) RunVectorEpisode(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[VectorActionRequest, VectorStepResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RLEnv_ServiceDesc.Streams[1], RLEnv_RunVectorEpisode_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[VectorActionRequest, VectorStepResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RLEnv_RunVectorEpisodeClient = grpc.BidiStreamingClient[VectorActionRequest, VectorStepResponse]

// RLEnvServer is the server API for RLEnv service.
// All implementations must embed UnimplementedRLEnvServer
// for forward compatibility.
//
// RLEnv exposes a single Mini Metro game instance for RL training.
//
// Typical usage per worker:
//  1. Call Info() once at startup to validate constants.
//  2. Call Reset() to begin an episode and receive the first observation.
//  3. Open a RunEpisode stream: send ActionRequests, receive StepResponses
//     until done=true.  Then call Reset() again for the next episode.
type RLEnvServer interface {
	// Info returns environment constants for startup validation.
	Info(context.Context, *Empty) (*InfoResponse, error)
	// Reset starts a new episode and returns the initial observation.
	Reset(context.Context, *ResetRequest) (*ResetResponse, error)
	// RunEpisode is a bidirectional stream for the inner training loop.
	// The client sends one ActionRequest per step; the server replies with
	// one StepResponse.  The stream stays open across steps within one episode.
	// When done=true in a StepResponse, call Reset() to begin the next episode
	// (the stream can be reused — send the next action after Reset returns).
	RunEpisode(grpc.BidiStreamingServer[ActionRequest, StepResponse]) error
	// Vectorized endpoints for scaling throughput.
	ResetVector(context.Context, *VectorResetRequest) (*VectorResetResponse, error)
	RunVectorEpisode(grpc.BidiStreamingServer[VectorActionRequest, VectorStepResponse]) error
	mustEmbedUnimplementedRLEnvServer()
}

// UnimplementedRLEnvServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRLEnvServer struct{}

func (UnimplementedRLEnvServer) Info(context.Context, *Empty) (*InfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedRLEnvServer) Reset(context.Context, *ResetRequest) (*ResetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedRLEnvServer) RunEpisode(grpc.BidiStreamingServer[ActionRequest, StepResponse]) error {
	return status.Error(codes.Unimplemented, "method RunEpisode not implemented")
}
func (UnimplementedRLEnvServer) ResetVector(context.Context, *VectorResetRequest) (*VectorResetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetVector not implemented")
}
func (UnimplementedRLEnvServer) RunVectorEpisode(grpc.BidiStreamingServer[VectorActionRequest, VectorStepResponse]) error {
	return status.Error(codes.Unimplemented, "method RunVectorEpisode not implemented")
}
func (UnimplementedRLEnvServer) mustEmbedUnimplementedRLEnvServer() {}
func (UnimplementedRLEnvServer) testEmbeddedByValue()               {}

// UnsafeRLEnvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RLEnvServer will
// result in compilation errors.
type UnsafeRLEnvServer interface {
	mustEmbedUnimplementedRLEnvServer()
}

func RegisterRLEnvServer(s grpc.ServiceRegistrar, srv RLEnvServer) {
	// If the following call panics, it indicates UnimplementedRLEnvServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RLEnv_ServiceDesc, srv)
}

func _RLEnv_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RLEnvServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RLEnv_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RLEnvServer).Info(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RLEnv_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RLEnvServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RLEnv_Reset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RLEnvServer).Reset(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RLEnv_RunEpisode_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RLEnvServer).RunEpisode(&grpc.GenericServerStream[ActionRequest, StepResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RLEnv_RunEpisodeServer = grpc.BidiStreamingServer[ActionRequest, StepResponse]

func _RLEnv_ResetVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RLEnvServer).ResetVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RLEnv_ResetVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RLEnvServer).ResetVector(ctx, req.(*VectorResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RLEnv_RunVectorEpisode_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RLEnvServer).RunVectorEpisode(&grpc.GenericServerStream[VectorActionRequest, VectorStepResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RLEnv_RunVectorEpisodeServer = grpc.BidiStreamingServer[VectorActionRequest, VectorStepResponse]

// RLEnv_ServiceDesc is the grpc.ServiceDesc for RLEnv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RLEnv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rl.RLEnv",
	HandlerType: (*RLEnvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _RLEnv_Info_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _RLEnv_Reset_Handler,
		},
		{
			MethodName: "ResetVector",
			Handler:    _RLEnv_ResetVector_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunEpisode",
			Handler:       _RLEnv_RunEpisode_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RunVectorEpisode",
			Handler:       _RLEnv_RunVectorEpisode_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "rl/proto/minimetro.proto",
}

const (
	Control_SetDifficulty_FullMethodName   = "/rl.Control/SetDifficulty"
	Control_SetComplexity_FullMethodName   = "/rl.Control/SetComplexity"
	Control_SetRewardConfig_FullMethodName = "/rl.Control/SetRewardConfig"
)

// ControlClient is the client API for Control service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Control exposes training-time knobs used by curriculum and evolutionary runs.
type ControlClient interface {
	SetDifficulty(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*Empty, error)
	SetComplexity(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*Empty, error)
	SetRewardConfig(ctx context.Context, in *RewardConfigRequest, opts ...grpc.CallOption) (*Empty, error)
}

type controlClient struct {
	cc grpc.ClientConnInterface
}

func NewControlClient(cc grpc.ClientConnInterface) ControlClient {
	return &controlClient{cc}
}

func (c *controlClient) SetDifficulty(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Control_SetDifficulty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) SetComplexity(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Control_SetComplexity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) SetRewardConfig(ctx context.Context, in *RewardConfigRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Control_SetRewardConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlServer is the server API for Control service.
// All implementations must embed UnimplementedControlServer
// for forward compatibility.
//
// Control exposes training-time knobs used by curriculum and evolutionary runs.
type ControlServer interface {
	SetDifficulty(context.Context, *ResetRequest) (*Empty, error)
	SetComplexity(context.Context, *ResetRequest) (*Empty, error)
	SetRewardConfig(context.Context, *RewardConfigRequest) (*Empty, error)
	mustEmbedUnimplementedControlServer()
}

// UnimplementedControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlServer struct{}

func (UnimplementedControlServer) SetDifficulty(context.Context, *ResetRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDifficulty not implemented")
}
func (UnimplementedControlServer) SetComplexity(context.Context, *ResetRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetComplexity not implemented")
}
func (UnimplementedControlServer) SetRewardConfig(context.Context, *RewardConfigRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRewardConfig not implemented")
}
func (UnimplementedControlServer) mustEmbedUnimplementedControlServer() {}
func (UnimplementedControlServer) testEmbeddedByValue()                 {}

// UnsafeControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlServer will
// result in compilation errors.
type UnsafeControlServer interface {
	mustEmbedUnimplementedControlServer()
}

func RegisterControlServer(s grpc.ServiceRegistrar, srv ControlServer) {
	// If the following call panics, it indicates UnimplementedControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Control_ServiceDesc, srv)
}

func _Control_SetDifficulty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).SetDifficulty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_SetDifficulty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).SetDifficulty(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_SetComplexity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).SetComplexity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_SetComplexity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).SetComplexity(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_SetRewardConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RewardConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).SetRewardConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_SetRewardConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).SetRewardConfig(ctx, req.(*RewardConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Control_ServiceDesc is the grpc.ServiceDesc for Control service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Control_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rl.Control",
	HandlerType: (*ControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetDifficulty",
			Handler:    _Control_SetDifficulty_Handler,
		},
		{
			MethodName: "SetComplexity",
			Handler:    _Control_SetComplexity_Handler,
		},
		{
			MethodName: "SetRewardConfig",
			Handler:    _Control_SetRewardConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rl/proto/minimetro.proto",
}

const (
	Inference_Act_FullMethodName = "/rl.Inference/Act"
)

// InferenceClient is the client API for Inference service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Inference is implemented by the Python inference server (infer.py).
// The Go live-game binary is the client (--rl-client flag).
type InferenceClient interface {
	Act(ctx context.Context, in *ActRequest, opts ...grpc.CallOption) (*ActionResponse, error)
}

type inferenceClient struct {
	cc grpc.ClientConnInterface
}

func NewInferenceClient(cc grpc.ClientConnInterface) InferenceClient {
	return &inferenceClient{cc}
}

func (c *inferenceClient) Act(ctx context.Context, in *ActRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, Inference_Act_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InferenceServer is the server API for Inference service.
// All implementations must embed UnimplementedInferenceServer
// for forward compatibility.
//
// Inference is implemented by the Python inference server (infer.py).
// The Go live-game binary is the client (--rl-client flag).
type InferenceServer interface {
	Act(context.Context, *ActRequest) (*ActionResponse, error)
	mustEmbedUnimplementedInferenceServer()
}

// UnimplementedInferenceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferenceServer struct{}

func (UnimplementedInferenceServer) Act(context.Context, *ActRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Act not implemented")
}
func (UnimplementedInferenceServer) mustEmbedUnimplementedInferenceServer() {}
func (UnimplementedInferenceServer) testEmbeddedByValue()                   {}

// UnsafeInferenceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferenceServer will
// result in compilation errors.
type UnsafeInferenceServer interface {
	mustEmbedUnimplementedInferenceServer()
}

func RegisterInferenceServer(s grpc.ServiceRegistrar, srv InferenceServer) {
	// If the following call panics, it indicates UnimplementedInferenceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Inference_ServiceDesc, srv)
}

func _Inference_Act_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServer).Act(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inference_Act_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServer).Act(ctx, req.(*ActRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Inference_ServiceDesc is the grpc.ServiceDesc for Inference service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Inference_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rl.Inference",
	HandlerType: (*InferenceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Act",
			Handler:    _Inference_Act_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rl/proto/minimetro.proto",
}
